Repository wecode-bootcamp-korea/24-1st-DotFriends-frontend, pull requests merged in 2021-09, with the labels that each got.

#7 [24기 박은정] [Footer] 레이아웃 구현완료
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#1 [주철진] ADD : 상품 리스트 페이지 기능 구현 완료
  public/data/ProductData.json
  public/images/mini.jpeg
  public/images/toystory.jpeg
  src/Routes.js
  src/config.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/component/Filters/Filters.js
  src/pages/ProductList/component/Filters/Filters.scss
  src/pages/ProductList/component/Pagination/Pagination.js
  src/pages/ProductList/component/Pagination/Pagination.scss
  src/pages/ProductList/component/Product/Product.js
  src/pages/ProductList/component/Product/Product.scss
  src/pages/ProductList/component/SideCategory/SideCategory.js
  src/pages/ProductList/component/SideCategory/SideCategory.scss
  src/pages/ProductList/component/Tags/Tags.js
  src/pages/ProductList/component/Tags/Tags.scss
  src/pages/ProductList/component/ViewController/ViewController.js
  src/pages/ProductList/component/ViewController/ViewController.scss
Labels: Status: 리뷰 요청

#8 [24기 박은정] Footer 레이아웃 수정완료
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#5 [주철진] ADD : 네비바 관련 기능 구현 완료
  src/Routes.js
  src/components/Nav/Category.js
  src/components/Nav/Category.scss
  src/components/Nav/MENULIST.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/styles/common.scss
Labels: Status: 추가 기능 구현중

#3 [24기 박은정] Fix : [Main] Conflict 해결완료
  public/images/next.png
  public/images/pre.png
  public/images/종모양.png
  src/Routes.js
  src/pages/Main/Goods/Goods.js
  src/pages/Main/Goods/Goods.scss
  src/pages/Main/GoodsList/GoodsList.js
  src/pages/Main/GoodsList/GoodsList.scss
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/styles/common.scss
Labels: Status: 리뷰 요청

#9 [주철진] ADD : 상세페이지 옵션 및 상품 더하기 빼기 기능 구현
  public/data/ProductDetail.json
  src/Routes.js
  src/config.js
  src/pages/Main/Main.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/ProductDetail.scss
  src/pages/ProductDetail/component/DetailCard/DetailCard.js
  src/pages/ProductDetail/component/DetailCard/DetailCard.scss
  src/pages/ProductDetail/component/Review/Review.js
  src/pages/ProductDetail/component/Review/Review.scss
  src/pages/ProductDetail/component/Star/Star.js
  src/pages/ProductDetail/component/Star/Star.scss
Labels: Status: 리뷰 요청

#2 [금보배]Add: Login 페이지 구현
  src/pages/Login/IdPwInput.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 수정 요청

#10 [주철진] ADD : 상품 리스트 페이지 modal 구현 완료
  src/config.js
  src/pages/ProductDetail/ProductDetail.js
  src/pages/ProductDetail/component/DetailCard/DetailCard.js
  src/pages/ProductList/ProductList.js
  src/pages/ProductList/ProductList.scss
  src/pages/ProductList/component/Product/Product.js
Labels: Status: 리뷰 요청

#4 [금보배]Add: SignUp 페이지 구현
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
  src/pages/SignUp/SignUpJoin.js
Labels: Status: 리뷰 요청
